package net.pawjwp.scarcity.config;

import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.event.config.ModConfigEvent;
import org.apache.commons.lang3.tuple.Pair;

// reference: https://cadiboo.github.io/tutorials/1.15.2/forge/3.3-config/

public class ScarcityConfig {

    public static final CommonConfig COMMON;
    public static final ForgeConfigSpec COMMON_SPEC;

    static {
        final Pair<CommonConfig, ForgeConfigSpec> specPair = new ForgeConfigSpec.Builder().configure(CommonConfig::new);
        COMMON_SPEC = specPair.getRight();
        COMMON = specPair.getLeft();
    }

    // fast regen
    public static int fastRegenFoodThreshold;
    public static int fastRegenIntervalTicks;
    public static float fastRegenSaturationCap;
    public static float fastRegenExhaustionMultiplier;

    // slow regen
    public static int slowRegenFoodThreshold;
    public static int slowRegenIntervalTicks;
    public static float slowRegenHealAmount;
    public static float slowRegenExhaustion;

    // exhaustion
    public static float exhaustionStep;
    public static float passiveExhaustionPerTick;

    public static void onLoad(final ModConfigEvent.Loading event) {
        if (event.getConfig().getSpec() == COMMON_SPEC) {
            bakeConfig();
        }
    }

    public static void onReload(final ModConfigEvent.Reloading event) {
        if (event.getConfig().getSpec() == COMMON_SPEC) {
            bakeConfig();
        }
    }

    public static void bakeConfig() {
        // fast regen
        fastRegenFoodThreshold = COMMON.fastRegenFoodThreshold.get();
        fastRegenIntervalTicks = COMMON.fastRegenIntervalTicks.get();
        fastRegenSaturationCap = COMMON.fastRegenSaturationCap.get().floatValue();
        fastRegenExhaustionMultiplier = COMMON.fastRegenExhaustionMultiplier.get().floatValue();

        // slow regen
        slowRegenFoodThreshold = COMMON.slowRegenFoodThreshold.get();
        slowRegenIntervalTicks = COMMON.slowRegenIntervalTicks.get();
        slowRegenHealAmount = COMMON.slowRegenHealAmount.get().floatValue();
        slowRegenExhaustion = COMMON.slowRegenExhaustion.get().floatValue();

        // exhaustion
        exhaustionStep = COMMON.exhaustionStep.get().floatValue();
        passiveExhaustionPerTick = COMMON.passiveExhaustionPerTick.get().floatValue();
    }

    public static class CommonConfig {
        // fast regen
        public final ForgeConfigSpec.IntValue fastRegenFoodThreshold;
        public final ForgeConfigSpec.IntValue fastRegenIntervalTicks;
        public final ForgeConfigSpec.DoubleValue fastRegenSaturationCap;
        public final ForgeConfigSpec.DoubleValue fastRegenExhaustionMultiplier;

        // slow regen
        public final ForgeConfigSpec.IntValue slowRegenFoodThreshold;
        public final ForgeConfigSpec.IntValue slowRegenIntervalTicks;
        public final ForgeConfigSpec.DoubleValue slowRegenHealAmount;
        public final ForgeConfigSpec.DoubleValue slowRegenExhaustion;

        // exhaustion
        public final ForgeConfigSpec.DoubleValue exhaustionStep;
        public final ForgeConfigSpec.DoubleValue passiveExhaustionPerTick;

        public CommonConfig(ForgeConfigSpec.Builder builder) {
            builder.push("food");
            builder.push("regen");
            builder.push("fast");

            fastRegenFoodThreshold = builder
                    .comment("Minimum hunger level required for fast regeneration to occur.")
                    .defineInRange("food_threshold", 20, 0, 20);

            fastRegenIntervalTicks = builder
                    .comment("How often fast regeneration heals, in ticks.")
                    .defineInRange("interval_ticks", 10, 1, 20_000);

            fastRegenSaturationCap = builder
                    .comment("Maximum saturation value used when calculating fast regeneration healing.")
                    .defineInRange("saturation_cap", 6.0, 0.0, 20.0);

            fastRegenExhaustionMultiplier = builder
                    .comment("Multiplier applied to exhaustion generated by fast regeneration.")
                    .defineInRange("exhaustion_multiplier", 1.0, 0.0, 10.0);

            builder.pop(); // fast

            builder.push("slow");

            slowRegenFoodThreshold = builder
                    .comment("Minimum hunger level required for slow regeneration to occur.")
                    .defineInRange("food_threshold", 18, 0, 20);

            slowRegenIntervalTicks = builder
                    .comment("How often slow regeneration heals, in ticks.")
                    .defineInRange("interval_ticks", 80, 1, 20_000);

            slowRegenHealAmount = builder
                    .comment("Amount of health restored per slow regeneration tick.")
                    .defineInRange("heal_amount", 1.0, 0.0, 20.0);

            slowRegenExhaustion = builder
                    .comment("Amount of exhaustion added per slow regeneration tick.")
                    .defineInRange("exhaustion", 6.0, 0.0, 40.0);

            builder.pop(); // slow
            builder.pop(); // regen

            builder.push("exhaustion");

            exhaustionStep = builder
                    .comment("How much exhaustion must accumulate before hunger or saturation is reduced.")
                    .comment("Functions as a global scale for hunger drain. Higher values mean slower hunger drain.")
                    .defineInRange("step", 4.0, 0.1, 40.0);

            passiveExhaustionPerTick = builder
                    .comment("Exhaustion added every tick regardless of player actions.")
                    .defineInRange("passive_per_tick", 0.0, 0.0, 40.0);

            builder.pop(); // exhaustion
            builder.pop(); // food
        }
    }
}